= 2022_07_01_PHP-Guestbook   (php Consolidation challenge)


== Learning objectives

* Storing data in files
* Converting complex constructs (array/objects) to string representation.
* Deliver a project under a strict deadline

=== The Mission
Let's remember the internet of the 1990, and create a classic widget that every site in that decade had: a guestbook.
(Any visitor on te page can leave a message on your page that are then saved and showed (last message on top)
for everybody who visits the page.)

==== Must-have features
* Posts must have the following attributes:
1. Title
2. Date
3. Content
4. Author name

* Use at least 2 classes: PostLoader & Post
* The messages are sorted from new (top) to old (bottom).
* Make sure the script can handle site defacement attacks: use htmlspecialchars() https://www.php.net/manual/en/function.htmlspecialchars.php
* Only show the latest 20 posts.

==== Nice to have features
* Profanity filter: at the top of your script create an array of "bad" words. If somebody tries to enter a message with those words, their messages gets rejected.
* When the user enters uses a "smily" like ":-)", ";-)", ":-(" replace it with an image of such a smily.
* Have an input field where the user can enter how many message he wants to see displayed.


== How to ?
====  store the messages:
* You can store the messages in a file on your system.
** file_get_contents() (Reads entire file into a string)  ( https://www.php.net/manual/en/function.file-get-contents.php )
This function is similar to file(), except that file_get_contents() returns the file in a string, starting at the specified offset up to length bytes.
On failure, file_get_contents() will return false.
** file_put_contents() (  )
* You can either use json_encode() or serialize() to convert your array to a string to store.
https://www.tutorialrepublic.com/php-tutorial/php-json-parsing.php

 <?php
          // Assign JSON encoded string to a PHP variable
 $json = '{"Peter":65,"Harry":80,"John":78,"Clark":90}';
         // Decode JSON data to PHP associative array
 $arr = json_decode($json, true);
         // Access values from the associative array
 echo $arr["Peter"];  // Output: 65
 echo $arr["Harry"];  // Output: 80
 echo $arr["John"];   // Output: 78
 echo $arr["Clark"];  // Output: 90
         // Decode JSON data to PHP object
 $obj = json_decode($json);
        // Access values from the returned object
 echo $obj->Peter;   // Output: 65
 echo $obj->Harry;   // Output: 80
 echo $obj->John;    // Output: 78
 echo $obj->Clark;   // Output: 90
 ?>

__Or use a foreach loop: __

 <?php
          // Assign JSON encoded string to a PHP variable
 $json = '{"Peter":65,"Harry":80,"John":78,"Clark":90}';
      // Decode JSON data to PHP associative array
 $arr = json_decode($json, true);
         // Loop through the associative array
 foreach($arr as $key=>$value){
 echo $key . "=>" . $value . "<br>";
  }
 echo "<hr>";
         // Decode JSON data to PHP object
 $obj = json_decode($json);
        // Loop through the object
 foreach($obj as $key=>$value){
 echo $key . "=>" . $value . "<br>";
 }
 ?>

__extract Values from Nested JSON data __

 $arr = json_decode($json, true);
         // Call the function and print all the values
 $result = printValues($arr);
 echo "<h3>" . $result["total"] . " value(s) found: </h3>";
 echo implode("<br>", $result["values"]);
 echo "<hr>";
         // Print a single value
 echo $arr["book"]["author"] . "<br>";  // Output: J. K. Rowling
 echo $arr["book"]["characters"][0] . "<br>";  // Output: Harry Potter
 echo $arr["book"]["price"]["hardcover"];  // Output: $20.32
 ?>


==== Tips & Advice
* To keep a good overview of the code we recommend separating the view (html code) as much as possible from the PHP code.
If you want you can already look into more advanced theory for this separation, but it is not required in this exercise.
* Write your footer and header HTML code and require() them in your template files in separate files to avoid repeating HTML code.
* What to work with json_encode: check out https://www.php.net/manual/en/jsonserializable.jsonserialize.php
 JsonSerializable::jsonSerialize — Specify data which should be serialized to JSON

==== Description
*public JsonSerializable::jsonSerialize(): mixed*

_Serializes the object to a value that can be serialized natively by json_encode()._

Parameters:  _This function has no parameters._

Return Values: _Returns data which can be serialized by json_encode(), which is a value of any type other than a resource._

* Examples

**Example #1 **JsonSerializable::jsonSerialize() example returning an array

    <?php
    class ArrayValue implements JsonSerializable {
    public function __construct(array $array) {
    $this->array = $array;
    }
            public function jsonSerialize() {
            return $this->array;
        }
    }
    $array = [1, 2, 3];
    echo json_encode(new ArrayValue($array), JSON_PRETTY_PRINT);
    ?>

The above example will output:

[ +
1, +
2, +
3 +
]

**Example #2 **JsonSerializable::jsonSerialize() example returning an associative array

 <?php
 class ArrayValue implements JsonSerializable {

 public function __construct(array $array) {
 $this->array = $array;
 }
  public function jsonSerialize() {
  return $this->array;
  }
 }
    $array = ['foo' => 'bar', 'quux' => 'baz'];
    echo json_encode(new ArrayValue($array), JSON_PRETTY_PRINT);
    ?>

The above example will output:
{ +
"foo": "bar", +
"quux": "baz" +
} +

*Example #3* JsonSerializable::jsonSerialize() example returning an int

    <?php
    class IntegerValue implements JsonSerializable {
    public function __construct($number) {
    $this->number = (integer) $number;
    }
        public function jsonSerialize() {
            return $this->number;
        }
    }
    echo json_encode(new IntegerValue(1), JSON_PRETTY_PRINT);
    ?>

The above example will output:
  1

*Example #4* JsonSerializable::jsonSerialize() example returning a string

    <?php
    class StringValue implements JsonSerializable {
    public function __construct($string) {
    $this->string = (string) $string;
    }
            public function jsonSerialize() {
            return $this->string;
        }
    }
        echo json_encode(new StringValue('Hello!'), JSON_PRETTY_PRINT);
    ?>

The above example will output:
"Hello!"

* Want to work with serialize: check out https://www.php.net/manual/en/language.oop5.magic.php#object.serialize

__serialize() and __unserialize()

 public __serialize(): array
 public __unserialize(array $data): void

serialize() checks if the class has a function with the magic name __serialize().
If so, that function is executed prior to any serialization. It must construct and return an associative
array of key/value pairs that represent the serialized form of the object. If no array is returned a TypeError
will be thrown.

Note:

If both __serialize() and __sleep() are defined in the same object, only __serialize() will
be called. __sleep() will be ignored. If the object implements the Serializable interface,
the interface's serialize() method will be ignored and __serialize() used instead.
